cmake_minimum_required(VERSION 3.24)
project(savepoint)

option(SAVEPOINT_SQLITE3 "Enable SQLite3 driver" ON)
option(SAVEPOINT_DEBUGGER "Enable Savepoint's debugger" OFF)

add_library(savepoint
    src/debug.cpp
    src/id.cpp
    src/log.cpp
    src/mutex.cpp
    src/null.cpp
    src/polymorph.cpp
    src/savepoint.cpp
    src/version.cpp
)
add_library(savepoint::savepoint ALIAS savepoint)
target_include_directories(savepoint PUBLIC include)
if(SAVEPOINT_DEBUGGER)
    target_compile_definitions(savepoint PUBLIC SAVEPOINT_DEBUGGER)
endif()
set_target_properties(savepoint PROPERTIES CXX_STANDARD 23)
set_target_properties(savepoint PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
target_precompile_headers(savepoint PUBLIC <savepoint/savepoint.hpp>)
if(SAVEPOINT_SQLITE3)
    add_subdirectory(lib/sqlite3)
    target_compile_definitions(savepoint PRIVATE SAVEPOINT_SQLITE3)
    target_link_libraries(savepoint PRIVATE savepoint_sqlite3)
    target_sources(savepoint PRIVATE src/sqlite3.cpp)
endif()

if(PROJECT_IS_TOP_LEVEL)
    set(BINARY_DIR ${CMAKE_BINARY_DIR}/bin)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BINARY_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${BINARY_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${BINARY_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BINARY_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${BINARY_DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${BINARY_DIR})
    add_subdirectory(lib/SDL)
    add_subdirectory(lib/glm)
    if(SAVEPOINT_DEBUGGER)
        add_subdirectory(lib/imgui)
    endif()
    function(savepoint_example NAME)
        set(TARGET savepoint_${NAME}_example)
        add_executable(${TARGET} examples/${NAME}.cpp)
        set_target_properties(${TARGET} PROPERTIES CXX_STANDARD 23)
        target_link_libraries(${TARGET} savepoint)
        add_test(NAME ${TARGET} COMMAND ${TARGET})
    endfunction()
    function(savepoint_app NAME)
        set(TARGET savepoint_${NAME}_example)
        add_executable(${TARGET} examples/${NAME}.cpp)
        set_target_properties(${TARGET} PROPERTIES CXX_STANDARD 23)
        target_link_libraries(${TARGET} SDL3::SDL3 glm savepoint savepoint_imgui)
    endfunction()
    savepoint_example(1_readme)
    savepoint_example(2_basic_usage)
    savepoint_example(3_std_types)
    savepoint_example(4_nested_types)
    savepoint_example(5_external_types)
    savepoint_example(6_spatial_types)
    savepoint_example(7_levels)
    savepoint_example(8_polymorphic_types)
    savepoint_example(9_version)
    savepoint_example(10_upgrading)
    savepoint_example(11_error_handling)
    savepoint_example(12_type_traits)
    savepoint_example(14_random)
    savepoint_example(15_reserved_ids)
    savepoint_example(16_basic_thread_safety)
    savepoint_example(17_concurrency)
    enable_testing()
    if(SAVEPOINT_DEBUGGER)
        savepoint_app(13_asteroids)
        savepoint_app(18_debugger)
    endif()
endif()
